---
- name: install custom package
  hosts: packs
  become: yes
  vars_files:
  - pkg_name.yml
  tasks:
  - meta: refresh_inventory
  - package:
      state: "{{ pkg_state }}"
      name: pkg_name
      use: auto 
